import { Meal } from '@/types'

// Datos de dieta - LUNES a DOMINGO (plan de hipertrofia)
export const DIET_DATA: Record<string, Meal[]> = {
  lunes: [
    {
      time: 'Desayuno (07:00)',
      calories: 680,
      foods: '🥣 100g Avena, 🥛 300ml Leche entera, 🍦 30g Proteína Whey, 🍌 1 Plátano, 🥜 20g Crema de cacahuete',
      macros: { p: 45, c: 85, f: 22 },
      prep: 'Batido potente para empezar el día con energía de sobra.',
      alternatives: [
        {
          foods: '🍳 4 huevos enteros revueltos con 🧀 50g queso cheddar, 🥑 1/2 aguacate sobre 🍞 2 rebanadas de pan integral.',
          calories: 685,
          macros: { p: 42, c: 40, f: 45 },
          prep: 'Opción alta en proteína y grasas para una energía sostenida.',
        },
      ],
    },
    {
      time: 'Almuerzo (11:00)',
      calories: 450,
      foods: '🍦 250g Yogur Griego natural, 🍎 1 Manzana, 🌰 30g Almendras',
      macros: { p: 28, c: 35, f: 23 },
      prep: 'Snack rico en proteína y grasas saludables para media mañana.',
    },
    {
      time: 'Comida (15:00, Pre-Entreno)',
      calories: 800,
      foods: '🍚 120g Arroz blanco (en seco), 🍗 200g Pechuga de pollo a la plancha, 🥦 150g Brócoli al vapor',
      macros: { p: 55, c: 125, f: 8 },
      prep: 'Comida alta en carbohidratos y fácil de digerir, ideal 90 min antes de entrenar.',
    },
    {
      time: 'Post-Entreno (18:30)',
      calories: 510,
      foods: '🥤 Batido: 40g Proteína Whey, 🍌 1 Plátano, 🥣 50g Avena instantánea, 🥛 300ml leche',
      macros: { p: 42, c: 65, f: 9 },
      prep: 'Recuperación rápida de glucógeno y proteína para el músculo.',
    },
    {
      time: 'Cena (21:30)',
      calories: 850,
      foods: '🐟 200g Salmón a la plancha, 🍚 120g Arroz basmati, 🥗 Ensalada grande con aceite de oliva',
      macros: { p: 50, c: 95, f: 30 },
      prep: 'Recuperación máxima y grasas omega-3 para reducir la inflamación.',
    },
  ],
  martes: [
    {
      time: 'Desayuno (07:00)',
      calories: 700,
      foods: '🍳 Revuelto de 4 huevos y 2 claras, 🥓 50g bacon, 🥑 1/2 aguacate, 🍞 2 rebanadas de pan integral',
      macros: { p: 45, c: 45, f: 40 },
      prep: 'Desayuno potente y saciante, alto en proteína y grasas.',
    },
    {
      time: 'Almuerzo (11:00)',
      calories: 450,
      foods: '🍖 100g Jamón serrano, 🍘 4 tortitas de arroz, 🍅 1 tomate en rodajas con aceite',
      macros: { p: 35, c: 40, f: 18 },
      prep: 'Snack salado, rápido y rico en proteínas.',
    },
    {
      time: 'Comida (15:00, Pre-Entreno)',
      calories: 850,
      foods: '🍠 450g Batata asada, 🥩 200g Filete de ternera, 🌿 Espárragos verdes',
      macros: { p: 58, c: 90, f: 28 },
      prep: 'Energía sostenida de la batata y el poder de la carne roja.',
    },
    {
      time: 'Post-Entreno (18:30)',
      calories: 450,
      foods: '🍘 6 tortitas de arroz, 🦃 120g pechuga de pavo y 🍯 20g de miel.',
      macros: { p: 35, c: 75, f: 3 },
      prep: 'Carbohidratos de rápida absorción y proteína magra.',
    },
    {
      time: 'Cena (21:30)',
      calories: 850,
      foods: '🍚 120g Arroz basmati, 🍛 200g Pollo al curry con leche de coco light, 🥦 Brócoli',
      macros: { p: 55, c: 110, f: 20 },
      prep: 'Una cena deliciosa y efectiva para la recuperación.',
    },
  ],
  miercoles: [
    {
      time: 'Desayuno (07:00)',
      calories: 750,
      foods: '🥞 4 Tortitas de avena y plátano (120g avena, 2 huevos, 1 plátano), 🍓 100g frutos rojos, 🍁 30ml sirope de arce',
      macros: { p: 40, c: 120, f: 15 },
      prep: 'Un desayuno lleno de carbohidratos para afrontar el día más duro de la semana.',
    },
    {
      time: 'Almuerzo (11:00)',
      calories: 450,
      foods: '🥤 Batido con 300ml leche, 🍌 1 plátano, 🥜 30g crema de cacahuete',
      macros: { p: 20, c: 45, f: 22 },
      prep: 'Snack líquido fácil de tomar y digerir.',
    },
    {
      time: 'Comida (15:00, Pre-Entreno)',
      calories: 850,
      foods: '🥔 500g Patata cocida, 🥩 200g Filete de ternera, 🥗 Ensalada verde con aceite de oliva',
      macros: { p: 58, c: 100, f: 25 },
      prep: 'Comida contundente para tener las reservas de energía a tope para las sentadillas.',
    },
    {
      time: 'Post-Entreno (18:30)',
      calories: 450,
      foods: '🥤 Batido con 300ml de leche, 🍦 40g de proteína whey y 🥣 50g de avena instantánea.',
      macros: { p: 45, c: 50, f: 10 },
      prep: 'La combinación perfecta de proteína y carbohidratos para después de entrenar pierna.',
    },
    {
      time: 'Cena (21:30)',
      calories: 850,
      foods: '🍔 Hamburguesa doble casera (200g ternera) en pan brioche, con queso, y 🍟 200g de patatas gajo al horno.',
      macros: { p: 60, c: 85, f: 32 },
      prep: 'Una recompensa merecida y muy efectiva para recuperarse.',
    },
  ],
  jueves: [
    {
      time: 'Desayuno (08:00)',
      calories: 600,
      foods: '🥣 100g Avena, 🥛 300ml Leche, 🍓 50g Frutos Rojos, 🌰 20g Almendras',
      macros: { p: 25, c: 85, f: 18 },
      prep: 'Un desayuno estándar y nutritivo.',
    },
    {
      time: 'Almuerzo (11:30)',
      calories: 430,
      foods: '🥚 3 huevos duros, 🍘 3 tortitas de arroz, 🥑 1/4 de aguacate',
      macros: { p: 25, c: 30, f: 23 },
      prep: 'Snack sencillo y alto en proteína.',
    },
    {
      time: 'Comida (15:00)',
      calories: 750,
      foods: '🌾 120g Quinoa, 🍗 200g Contramuslos de pollo deshuesados, 🌶️ Pimientos asados',
      macros: { p: 50, c: 80, f: 25 },
      prep: 'Comida completa con proteína de calidad y carbohidratos complejos.',
    },
    {
      time: 'Cena (21:00)',
      calories: 800,
      foods: '🥗 Ensalada César grande: 🥬 Mezclum, 🍗 200g pollo a la plancha, 🍞 picatostes, 🧀 lascas de parmesano y salsa césar.',
      macros: { p: 55, c: 40, f: 45 },
      prep: 'Cena más ligera en carbos para el día de descanso.',
    },
  ],
  viernes: [
    {
      time: 'Desayuno (07:00)',
      calories: 680,
      foods: '🥣 100g Avena, 🥛 300ml Leche entera, 🍦 30g Proteína Whey, 🍌 1 Plátano, 🥜 20g Crema de cacahuete',
      macros: { p: 45, c: 85, f: 22 },
      prep: 'Repetimos el batido potente, es una fórmula ganadora.',
    },
    {
      time: 'Almuerzo (11:00)',
      calories: 450,
      foods: '🍦 250g Yogur Griego natural, 🍎 1 Manzana, 🌰 30g Almendras',
      macros: { p: 28, c: 35, f: 23 },
      prep: 'Snack rico en proteína y grasas saludables.',
    },
    {
      time: 'Comida (15:00, Pre-Entreno)',
      calories: 800,
      foods: '🍚 120g Arroz blanco (en seco), 🍗 200g Pechuga de pollo a la plancha, 🍅 Tomate en rodajas',
      macros: { p: 55, c: 125, f: 8 },
      prep: 'Energía rápida para un entrenamiento intenso de hombros.',
    },
    {
      time: 'Post-Entreno (18:30)',
      calories: 500,
      foods: '🥤 Batido: 40g Proteína Whey, 🍌 1 Plátano, 🥣 50g Avena instantánea, 🥛 300ml leche',
      macros: { p: 42, c: 65, f: 9 },
      prep: 'Recuperación inmediata post-entreno.',
    },
    {
      time: 'Cena (21:30)',
      calories: 820,
      foods: '🍝 120g Pasta (en seco), 🐟 2 latas de atún, 🍅 sofrito de tomate y cebolla, 🌿 orégano',
      macros: { p: 60, c: 110, f: 15 },
      prep: 'Recuperación alta en proteína y carbohidratos con poca grasa.',
    },
  ],
  sabado: [
    {
      time: 'Desayuno (Flexible)',
      calories: 700,
      foods: '🍳 Revuelto de 4 huevos y 2 claras, 🥓 50g bacon, 🥑 1/2 aguacate, 🍞 2 rebanadas de pan integral',
      macros: { p: 45, c: 45, f: 40 },
      prep: 'Desayuno potente para empezar el fin de semana entrenando duro.',
    },
    {
      time: 'Almuerzo (Flexible)',
      calories: 450,
      foods: '🍖 100g Jamón serrano, 🍘 4 tortitas de arroz, 🍅 1 tomate en rodajas con aceite',
      macros: { p: 35, c: 40, f: 18 },
      prep: 'Un clásico que nunca falla.',
    },
    {
      time: 'Comida (Pre-Entreno, ~2h antes)',
      calories: 850,
      foods: '🍠 450g Batata asada, 🥩 180g de lomo de cerdo a la plancha, 🥦 brócoli',
      macros: { p: 55, c: 90, f: 28 },
      prep: 'Energía sostenida para el peso muerto y el hip thrust.',
    },
    {
      time: 'Post-Entreno',
      calories: 450,
      foods: '🍘 6 tortitas de arroz, 🦃 120g pechuga de pavo y 🍯 20g de miel.',
      macros: { p: 35, c: 75, f: 3 },
      prep: 'Carbohidratos de rápida absorción y proteína magra.',
    },
    {
      time: 'Cena (Flexible)',
      calories: 850,
      foods: '🍚 120g Arroz basmati, 🍛 200g Pollo al curry con leche de coco light, 🌿 espinacas',
      macros: { p: 55, c: 110, f: 20 },
      prep: 'Una cena deliciosa y efectiva para la recuperación.',
    },
  ],
  domingo: [
    {
      time: 'Desayuno Libre',
      calories: 600,
      foods: '🥞 Tortitas con sirope y frutas, o 🥐 bollería variada',
      macros: { p: 20, c: 90, f: 18 },
      prep: '¡Disfruta del domingo! Escoge lo que más te apetezca.',
    },
    {
      time: 'Comida Principal Libre',
      calories: 1200,
      foods: '🍕 Pizza mediana, 🍔 hamburguesa completa o 🥘 una buena ración de paella',
      macros: { p: 55, c: 120, f: 50 },
      prep: 'La comida principal del día, sin remordimientos. Es parte del plan para recargar pilas y mente.',
    },
    {
      time: 'Cena Ligera',
      calories: 650,
      foods: '🍣 Bandeja de sushi variado (12-15 piezas) o 🥗 Ensalada César grande con pollo',
      macros: { p: 40, c: 80, f: 20 },
      prep: 'Algo más controlado para terminar el día, pero igualmente delicioso.',
    },
    {
      time: 'Snacks Flexibles',
      calories: 800,
      foods: '🍿 Palomitas, 🍦 helado, 🍫 chocolate... Reparte estas calorías como quieras a lo largo del día.',
      macros: { p: 15, c: 120, f: 30 },
      prep: 'Disfruta de tus antojos. Mañana volvemos al plan.',
    },
  ],
}
